name: Provision Lab

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      SUBSCRIPTION_ID: 
        required: true
        default: "xxx-xxx-xxx"

      DOMAIN: 
        required: true
        default: "xxx.com"

      LAB_NAME: 
        required: true
        default: 'lab1'

      LAB_USER_COUNT: 
        required: true
        default: 2

jobs:
  provision_lab:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/CLI@v1

    - name: Run provision_lab.ps1
      shell: pwsh
      run: |
        ./provision_lab.ps1 `
          -subscriptionId ${{ github.event.inputs.SUBSCRIPTION_ID }} `
          -domain ${{ github.event.inputs.DOMAIN }} `
          -labName ${{ github.event.inputs.LAB_NAME }} `
          -labUserCount ${{ github.event.inputs.LAB_USER_COUNT }}


          